### PR TITLE
Support qBittorrent 4.4.0

### LINKED ISSUE #59: qBittorrent Next Release
Filter torrent info endpoint by tag - qbittorrent/qbittorrent#15152
Add "Forced metadata downloading" state - qbittorrent/qbittorrent#15185
Support per-torrent/per-category "download folder" - qbittorrent/qbittorrent#15793

### PR DESCRIPTION
**Pull request by rmartin16**
Fixes #59 

* Filter torrent info endpoint by tag - qbittorrent/qBittorrent#15152
* Add "Forced metadata downloading" state - qbittorrent/qBittorrent#15185
* Support per-torrent/per-category "download folder" - qbittorrent/qbittorrent#15793

**Release Checklist**
- [x] Bump version number
- [x] Update qBittorrent version/link in docs
- [x] Update CHANGELOG
- [x] Update qBittorrent version/link in README

Update `v4.4.0beta2` in `conftest.py` to `v4.4.0` before merging.

### CODE REVIEW

**Comment by jules-datascientest** [comment]
Hi ! Is there any news on when this will be out ? I'm using the webapi version `2.8.2` and auth doesn't seem to work :/

**Comment by rmartin16** [comment]
Hello @jules-datascientest. Im currently just waiting on qBittorrent to actually drop v4.4.0....they released `rc1` recently.

Nonetheless, using the released version of `qbittorrent-api` should work fine against v2.8.2. Can you open up an issue with some details on what's happening? I'm sure we can get it addressed. Thanks.

**Comment by rmartin16** [comment]
(for posterity)
I moved all of the other changes in to separate PRs since the qbittorrent team is taking longer than expected to release 4.4.0.

**Comment by rmartin16** [comment]
qBittorrent released v4.4.0 rather quickly after merging qbittorrent/qBittorrent#15793....this merge introduced several changes to the web api...some likely unintended (see qbittorrent/qbittorrent#15969 as an example).

I normally try to smooth out qBittorrent API version differences.....but the change of the dictionary key `savePath` to `save_path` for `torrents/categories` stresses the ability for this client to cover that up because of the way HTTP responses are generically processed after getting them back from qBittorrent....so, I don't think I'll easily be able to change `save_path` back to `savePath` before returning the dictionary back to calling code.

**Pull request merged**
